crnk:
  resourcePackage: com.lanzonprojects.noteskeeper.domain
  domainName: http://localhost:9090/lanzonprojects
  pathPrefix: /api
  default-page-limit: 20

management:
  server:
    context-path: /lanzonprojects
    port: 9090